### ISSUE TITLE
Code has mixed use of [[ ]] and [ ]

### ISSUE THREAD

**Issue by z0rc** [MikeDacre/tmux-zsh-vim-titles#4]
Please use `[[ ]]` everywhere for consistency.

**Comment by MikeDacre** [comment]
I can do that in the ZSH plugin, but I won't change it in the tmux and bash code, because the `[ ]` test works more places, and I want the tmux plugin to work even if tmux is launched from a really old shell. Plus it doesn't really make that much difference, the old-style POSIX brackets work great for unary comparisons.

**Comment by MikeDacre** [comment]
I am not convinced this is necessary. I have always used single brackets wherever possible, particularly for unary comparisons. I only use the double brackets for tests that require the new style. I guess that is unnecessary, particularly for ZSH, but it is what I have always done. I might change it, not sure yet.

**Comment by MikeDacre** [comment]
Yeah, I don't want to change this. The single brackets add no bugs and that is just the syntax I always use these days: no brackets for checking a true/false variable or a program exit code, one bracket for unary tests, like `-f`, and two brackets for more modern logic. That makes sense, and while it isn't strictly necessary, it doesn't hurt anyone, so I am just leaving it as is.
